stages:          # List of stages for jobs, and their order of execution
  - build
  - docker

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: python:3.12-bullseye
  script:
    - cd $(pwd)/DjangoProjects/DateBase
    - pwd
    - pip install -r requirements.txt
    - ls -al
    - python manage.py runserver &
    - sleep 10
    - curl -sSf http://localhost:8000 > /dev/null && echo "Server is Up"
    - echo "All tests successfully passed."


docker-job:
  stage: docker
  image: 
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script: 
    - pwd
    - VERSION=$(grep 'VERSION =' DjangoProjects/DateBase/DateBase/settings.py | cut -d'=' -f2 | tr -d ' ')
    - BUILD_NAME="django-database"
    - echo ${REGISTRY_ADDR}/${CI_PROJECT_PATH}/$BUILD_NAME:$VERSION
    - echo ${AUTH_TOKEN} | base64 -d > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context "$(pwd)/DjangoProjects/DateBase" \
        --dockerfile "$(pwd)/DjangoProjects/DateBase/Dockerfile" \
        --destination "${REGISTRY_ADDR}/${CI_PROJECT_PATH}/$BUILD_NAME:$VERSION"