# Generated by Django 5.1.4 on 2025-02-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DateBaseApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
