# Generated by Django 5.1.4 on 2025-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateBaseApp', '0006_logfordeleteusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiBotsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('status', models.CharField(default='bot', max_length=4)),
            ],
        ),
    ]
