# Generated by Django 5.1.4 on 2025-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateBaseApp', '0007_antibotslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('trying', models.IntegerField(default=0)),
            ],
        ),
    ]
