# Generated by Django 5.1.4 on 2025-02-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateBaseApp', '0008_ipallusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipallusers',
            name='time_blocked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ipallusers',
            name='time_unblocked',
            field=models.DateTimeField(null=True),
        ),
    ]
