# Generated by Django 5.1.4 on 2025-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateBaseApp', '0009_ipallusers_time_blocked_ipallusers_time_unblocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='ipallusers',
            name='time_blocked',
            field=models.DateTimeField(null=True),
        ),
    ]
