# Generated by Django 5.1.4 on 2025-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateBaseApp', '0010_files_alter_ipallusers_time_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='home/')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
