# Generated by Django 5.1.4 on 2025-02-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DateBaseApp', '0011_filemodel_delete_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='home/vlados/'),
        ),
    ]
