"""
Django settings for CampSite project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-35a=5&!s2=8m1ecr20wm&c*q!i9+u8kw27!^t6^p!e(#i^7gt*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['campsite.dbystritskiy.ru', '127.0.0.1', 'localhost']

# LOGGING SETTINGS

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logger.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
    'CampSiteApp',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',


]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <- добавь сюда, должен быть выше CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "https://campsite.dbystritskiy.ru",
]

ROOT_URLCONF = 'CampSite.urls'

AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

"""Настройка keycloak """
LOGOUT_REDIRECT_URL = 'https://campsite.dbystritskiy.ru/'
LOGIN_REDIRECT_URL = '/api/me/v1/keycloak'
LOGIN_URL = '/auth'
OIDC_CALLBACK_URL = "https://campsite.dbystritskiy.ru/auth/oidc/callback/"
OIDC_RP_CLIENT_ID = 'django-backend'  # Client ID из Keycloak
OIDC_RP_CLIENT_SECRET = 'UV6CHPFIhbrgB3vh7qFZGo0rCkGWXcbQ'  # Client Secret из Keycloak
OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://campsite.dbystritskiy.ru/auth/realms/myrealm/protocol/openid-connect/auth'
OIDC_OP_TOKEN_ENDPOINT = 'https://campsite.dbystritskiy.ru/auth/realms/myrealm/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = 'https://campsite.dbystritskiy.ru/auth/realms/myrealm/protocol/openid-connect/userinfo'
OIDC_OP_JWKS_ENDPOINT = 'https://campsite.dbystritskiy.ru/auth/realms/myrealm/protocol/openid-connect/certs'
OIDC_OP_LOGOUT_ENDPOINT = 'https://campsite.dbystritskiy.ru/auth/realms/myrealm/protocol/openid-connect/logout'
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True
OIDC_STORE_REFRESH_TOKEN = True
OIDC_CREATE_USER = True
KEYCLOAK_HOST = "https://campsite.dbystritskiy.ru"
REALM = "myrealm"
CLIENT_ID = "django-backend"
CLIENT_SECRET = "UV6CHPFIhbrgB3vh7qFZGo0rCkGWXcbQ"
KEYCLOAK_LOGIN = "https://campsite.dbystritskiy.ru/auth/realms/myrealm/protocol/openid-connect/token"



WSGI_APPLICATION = 'CampSite.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'CampSiteApp.authentication.TokenLifeTime.ExpiringTokenAuthentication',
        'mozilla_django_oidc.contrib.drf.OIDCAuthentication',
        'CampSiteApp.authentication.keycloak.KeycloakAuthentication',
    ),
}




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'backenddb',  # Имя базы в нижнем регистре!
        'USER': 'backend',
        'PASSWORD': 'backend1234!',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # можешь указать путь к своим шаблонам
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'CampSiteApp.UserModel'
#
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

#For pipline
VERSION = 2.3
#fix


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'your_email@yandex.ru'
EMAIL_HOST_PASSWORD = 'your_app_password'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER


STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
